
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BE4063BF78C8E0DFD21FBA38CFAB95F6'
    
_lr_action_items = {'scroll':([0,3,5,6,7,9,20,22,28,32,],[4,4,4,4,-11,4,-10,-12,-9,-13,]),'rbracket':([15,18,26,31,],[20,22,28,32,]),'$end':([1,3,5,6,7,9,11,13,14,17,20,22,28,32,],[0,-6,-4,-2,-11,-8,-5,-3,-1,-7,-10,-12,-9,-13,]),'touch':([0,3,5,6,7,9,20,22,28,32,],[7,7,7,7,-11,7,-10,-12,-9,-13,]),'wait':([0,3,5,6,7,9,20,22,28,32,],[2,2,2,2,-11,2,-10,-12,-9,-13,]),'lbracket':([2,4,7,8,],[10,12,15,16,]),'move':([0,3,5,6,7,9,20,22,28,32,],[8,8,8,8,-11,8,-10,-12,-9,-13,]),'separator':([19,21,25,29,],[23,24,27,30,]),'digit':([10,12,16,23,24,27,30,],[18,19,21,25,26,29,31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commande':([0,3,5,6,9,],[1,11,13,14,17,]),'scroller':([0,3,5,6,9,],[9,9,9,9,9,]),'attendre':([0,3,5,6,9,],[5,5,5,5,5,]),'bouger':([0,3,5,6,9,],[6,6,6,6,6,]),'toucher':([0,3,5,6,9,],[3,3,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('commande -> bouger commande','commande',2,'p_move','robot.py',71),
  ('commande -> bouger','commande',1,'p_move','robot.py',72),
  ('commande -> attendre commande','commande',2,'p_move','robot.py',73),
  ('commande -> attendre','commande',1,'p_move','robot.py',74),
  ('commande -> toucher commande','commande',2,'p_move','robot.py',75),
  ('commande -> toucher','commande',1,'p_move','robot.py',76),
  ('commande -> scroller commande','commande',2,'p_move','robot.py',77),
  ('commande -> scroller','commande',1,'p_move','robot.py',78),
  ('bouger -> move lbracket digit separator digit rbracket','bouger',6,'p_bouger','robot.py',82),
  ('toucher -> touch lbracket rbracket','toucher',3,'p_toucher','robot.py',90),
  ('toucher -> touch','toucher',1,'p_toucher','robot.py',91),
  ('attendre -> wait lbracket digit rbracket','attendre',4,'p_attendre','robot.py',99),
  ('scroller -> scroll lbracket digit separator digit separator digit separator digit rbracket','scroller',10,'p_scroller','robot.py',106),
]
