
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '5F72E1458B803AF599AC1E24B24C2BFA'
    
_lr_action_items = {'rbracket':([13,23,29,34,],[21,26,31,35,]),'separator':([22,24,28,32,],[25,27,30,33,]),'touch':([0,1,2,3,5,6,8,11,21,26,31,35,],[2,2,-13,2,2,2,2,-16,-12,-14,-11,-15,]),'move':([0,1,2,3,5,6,8,11,21,26,31,35,],[10,10,-13,10,10,10,10,-16,-12,-14,-11,-15,]),'digit':([17,19,20,25,27,30,33,],[22,23,24,28,29,32,34,]),'scroll':([0,1,2,3,5,6,8,11,21,26,31,35,],[7,7,-13,7,7,7,7,-16,-12,-14,-11,-15,]),'$end':([1,2,3,4,5,6,8,11,12,14,15,16,18,21,26,31,35,],[-2,-13,-6,0,-10,-8,-4,-16,-1,-5,-9,-7,-3,-12,-14,-11,-15,]),'wait':([0,1,2,3,5,6,8,11,21,26,31,35,],[9,9,-13,9,9,9,9,-16,-12,-14,-11,-15,]),'return':([0,1,2,3,5,6,8,11,21,26,31,35,],[11,11,-13,11,11,11,11,-16,-12,-14,-11,-15,]),'lbracket':([2,7,9,10,],[13,17,19,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toucher':([0,1,3,5,6,8,],[3,3,3,3,3,3,]),'commande':([0,1,3,5,6,8,],[4,12,14,15,16,18,]),'attendre':([0,1,3,5,6,8,],[8,8,8,8,8,8,]),'retourner':([0,1,3,5,6,8,],[5,5,5,5,5,5,]),'scroller':([0,1,3,5,6,8,],[6,6,6,6,6,6,]),'bouger':([0,1,3,5,6,8,],[1,1,1,1,1,1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('commande -> bouger commande','commande',2,'p_move','robot.py',71),
  ('commande -> bouger','commande',1,'p_move','robot.py',72),
  ('commande -> attendre commande','commande',2,'p_move','robot.py',73),
  ('commande -> attendre','commande',1,'p_move','robot.py',74),
  ('commande -> toucher commande','commande',2,'p_move','robot.py',75),
  ('commande -> toucher','commande',1,'p_move','robot.py',76),
  ('commande -> scroller commande','commande',2,'p_move','robot.py',77),
  ('commande -> scroller','commande',1,'p_move','robot.py',78),
  ('commande -> retourner commande','commande',2,'p_move','robot.py',79),
  ('commande -> retourner','commande',1,'p_move','robot.py',80),
  ('bouger -> move lbracket digit separator digit rbracket','bouger',6,'p_bouger','robot.py',85),
  ('toucher -> touch lbracket rbracket','toucher',3,'p_toucher','robot.py',92),
  ('toucher -> touch','toucher',1,'p_toucher','robot.py',93),
  ('attendre -> wait lbracket digit rbracket','attendre',4,'p_attendre','robot.py',100),
  ('scroller -> scroll lbracket digit separator digit separator digit separator digit rbracket','scroller',10,'p_scroller','robot.py',106),
  ('retourner -> return','retourner',1,'p_retourner','robot.py',113),
]
