
# C:\Users\Administrateur\Desktop\project Dobot\Python Dobot\Windows Dobot Tester\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'BE4063BF78C8E0DFD21FBA38CFAB95F6'
    
_lr_action_items = {'digit':([12,16,17,22,23,28,30,],[18,20,21,25,26,29,31,]),'move':([0,1,2,4,6,7,19,24,27,32,],[3,3,3,3,-11,3,-10,-12,-9,-13,]),'lbracket':([3,6,8,9,],[12,14,16,17,]),'separator':([18,20,26,29,],[22,23,28,30,]),'touch':([0,1,2,4,6,7,19,24,27,32,],[6,6,6,6,-11,6,-10,-12,-9,-13,]),'rbracket':([14,21,25,31,],[19,24,27,32,]),'wait':([0,1,2,4,6,7,19,24,27,32,],[9,9,9,9,-11,9,-10,-12,-9,-13,]),'scroll':([0,1,2,4,6,7,19,24,27,32,],[8,8,8,8,-11,8,-10,-12,-9,-13,]),'$end':([1,2,4,5,6,7,10,11,13,15,19,24,27,32,],[-6,-8,-2,0,-11,-4,-5,-7,-1,-3,-10,-12,-9,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toucher':([0,1,2,4,7,],[1,1,1,1,1,]),'bouger':([0,1,2,4,7,],[4,4,4,4,4,]),'attendre':([0,1,2,4,7,],[7,7,7,7,7,]),'commande':([0,1,2,4,7,],[5,10,11,13,15,]),'scroller':([0,1,2,4,7,],[2,2,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('commande -> bouger commande','commande',2,'p_move','robot.py',71),
  ('commande -> bouger','commande',1,'p_move','robot.py',72),
  ('commande -> attendre commande','commande',2,'p_move','robot.py',73),
  ('commande -> attendre','commande',1,'p_move','robot.py',74),
  ('commande -> toucher commande','commande',2,'p_move','robot.py',75),
  ('commande -> toucher','commande',1,'p_move','robot.py',76),
  ('commande -> scroller commande','commande',2,'p_move','robot.py',77),
  ('commande -> scroller','commande',1,'p_move','robot.py',78),
  ('bouger -> move lbracket digit separator digit rbracket','bouger',6,'p_bouger','robot.py',82),
  ('toucher -> touch lbracket rbracket','toucher',3,'p_toucher','robot.py',90),
  ('toucher -> touch','toucher',1,'p_toucher','robot.py',91),
  ('attendre -> wait lbracket digit rbracket','attendre',4,'p_attendre','robot.py',99),
  ('scroller -> scroll lbracket digit separator digit separator digit separator digit rbracket','scroller',10,'p_scroller','robot.py',106),
]
