
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'digit lbracket rbracket separator move touch wait scrollcommande : bouger commande\n                     | bouger\n                     | attendre commande\n                     | attendre\n                     | toucher commande\n                     | toucher\n                     | scroller commande\n                     | scroller\n                      bouger : move lbracket digit separator digit rbracket toucher : touch lbracket rbracket\n                        | touch\n                         attendre : wait lbracket digit rbracket scroller : scroll lbracket digit separator digit separator digit separator digit rbracket'
    
_lr_action_items = {'move':([0,2,3,6,8,9,19,24,27,32,],[1,1,-11,1,1,1,-10,-12,-9,-13,]),'digit':([10,13,15,22,23,28,30,],[18,20,21,25,26,29,31,]),'touch':([0,2,3,6,8,9,19,24,27,32,],[3,3,-11,3,3,3,-10,-12,-9,-13,]),'lbracket':([1,3,4,7,],[10,12,13,15,]),'$end':([2,3,5,6,8,9,11,14,16,17,19,24,27,32,],[-6,-11,0,-2,-4,-8,-5,-1,-3,-7,-10,-12,-9,-13,]),'scroll':([0,2,3,6,8,9,19,24,27,32,],[4,4,-11,4,4,4,-10,-12,-9,-13,]),'wait':([0,2,3,6,8,9,19,24,27,32,],[7,7,-11,7,7,7,-10,-12,-9,-13,]),'separator':([18,20,26,29,],[22,23,28,30,]),'rbracket':([12,21,25,31,],[19,24,27,32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commande':([0,2,6,8,9,],[5,11,14,16,17,]),'toucher':([0,2,6,8,9,],[2,2,2,2,2,]),'attendre':([0,2,6,8,9,],[8,8,8,8,8,]),'scroller':([0,2,6,8,9,],[9,9,9,9,9,]),'bouger':([0,2,6,8,9,],[6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('commande -> bouger commande','commande',2,'p_move','robot.py',71),
  ('commande -> bouger','commande',1,'p_move','robot.py',72),
  ('commande -> attendre commande','commande',2,'p_move','robot.py',73),
  ('commande -> attendre','commande',1,'p_move','robot.py',74),
  ('commande -> toucher commande','commande',2,'p_move','robot.py',75),
  ('commande -> toucher','commande',1,'p_move','robot.py',76),
  ('commande -> scroller commande','commande',2,'p_move','robot.py',77),
  ('commande -> scroller','commande',1,'p_move','robot.py',78),
  ('bouger -> move lbracket digit separator digit rbracket','bouger',6,'p_bouger','robot.py',82),
  ('toucher -> touch lbracket rbracket','toucher',3,'p_toucher','robot.py',90),
  ('toucher -> touch','toucher',1,'p_toucher','robot.py',91),
  ('attendre -> wait lbracket digit rbracket','attendre',4,'p_attendre','robot.py',99),
  ('scroller -> scroll lbracket digit separator digit separator digit separator digit rbracket','scroller',10,'p_scroller','robot.py',106),
]
