
# C:\Users\Administrateur\Desktop\project Dobot\Python Dobot\robot langage\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'AAC26FA08E1C658BE3E693C10E29EC79'
    
_lr_action_items = {'digit':([9,13,17,],[14,16,19,]),'move':([0,1,3,5,6,15,18,20,],[2,2,2,-9,2,-8,-10,-7,]),'lbracket':([2,5,7,],[9,11,13,]),'separator':([14,],[17,]),'touch':([0,1,3,5,6,15,18,20,],[5,5,5,-9,5,-8,-10,-7,]),'rbracket':([11,16,19,],[15,18,20,]),'wait':([0,1,3,5,6,15,18,20,],[7,7,7,-9,7,-8,-10,-7,]),'$end':([1,3,4,5,6,8,10,12,15,18,20,],[-6,-2,0,-9,-4,-5,-1,-3,-8,-10,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toucher':([0,1,3,6,],[1,1,1,1,]),'bouger':([0,1,3,6,],[3,3,3,3,]),'attendre':([0,1,3,6,],[6,6,6,6,]),'commande':([0,1,3,6,],[4,8,10,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commande","S'",1,None,None,None),
  ('commande -> bouger commande','commande',2,'p_move','robot.py',56),
  ('commande -> bouger','commande',1,'p_move','robot.py',57),
  ('commande -> attendre commande','commande',2,'p_move','robot.py',58),
  ('commande -> attendre','commande',1,'p_move','robot.py',59),
  ('commande -> toucher commande','commande',2,'p_move','robot.py',60),
  ('commande -> toucher','commande',1,'p_move','robot.py',61),
  ('bouger -> move lbracket digit separator digit rbracket','bouger',6,'p_bouger','robot.py',66),
  ('toucher -> touch lbracket rbracket','toucher',3,'p_toucher','robot.py',71),
  ('toucher -> touch','toucher',1,'p_toucher','robot.py',72),
  ('attendre -> wait lbracket digit rbracket','attendre',4,'p_attendre','robot.py',78),
]
